schema: "classroom50/repo-config/v1"
classroom: "l5-adv-2026-jul"
assignment: "l5-adv-mission-5-phase-1"
owner:
  username: "bu-missionreadyhq"
  id: 279871601
  accepted_at: "2026-09-09T09:27:38Z"
source:
  owner: "Mission-Ready"
  owner_id: 91437324
  repo: "l5-adv-mission-5-phase1"
  branch: "main"
